 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/personajes", type: :request do
  
  # Personaje. As you add validations to Personaje, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  let(:personaje) { create :personaje }

  describe "GET /index" do
    it "renders a successful response" do
      Personaje.create! valid_attributes
      get personajes_url
      expect(response).to have_http_status :ok
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      get personaje_url(personaje)
      expect(response).to have_http_status :found
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_personaje_url
      expect(response).to have_http_status :ok
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      get edit_personaje_url(personaje)
      expect(response).to have_http_status :ok
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Personaje" do
        expect {
          post personajes_url, params: { personaje: valid_attributes }
        }.to change(Personaje, :count).by(1)
      end

      it "redirects to the created personaje" do
        post personajes_url, params: { personaje: valid_attributes }
        expect(response).to redirect_to(personaje_url(Personaje.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Personaje" do
        expect {
          post personajes_url, params: { personaje: invalid_attributes }
        }.to change(Personaje, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post personajes_url, params: { personaje: invalid_attributes }
        expect(response).to have_http_status :ok
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested personaje" do
          patch personaje_url(personaje), params: { personaje: new_attributes }
        personaje.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the personaje" do
          patch personaje_url(personaje), params: { personaje: new_attributes }
        personaje.reload
        expect(response).to redirect_to(personaje_url(personaje))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
          patch personaje_url(personaje), params: { personaje: invalid_attributes }
        expect(response).to have_http_status :ok
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested personaje" do
      personaje
      expect {
        delete personaje_url(personaje)
      }.to change(Personaje, :count).by(-1)
    end

    it "redirects to the personajes list" do
      delete personaje_url(personaje)
      expect(response).to redirect_to(personajes_url)
    end
  end
end
