name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Clone code repo
      uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
    - run: bundle lock --add-platform x86_64-linux
    - name: Build and run unit tests with Buildpack CI
      uses: buildpack-ci/run-tests@v1
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/test
        RAILS_ENV: test
        DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
        BUILDPACK_URL: https://github.com/heroku/heroku-buildpack-ruby.git
